# Generated by Django 5.2.10 on 2026-01-29 13:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("head", "Head/Face"),
                            ("trunk", "Trunk"),
                            ("upper_limb", "Upper Limb"),
                            ("lower_limb", "Lower Limb"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="WoundType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("acute", "Acute Wound"),
                            ("chronic", "Chronic Wound"),
                            ("surgical", "Surgical Wound"),
                            ("trauma", "Trauma Wound"),
                            ("burn", "Burn Wound"),
                            ("ulcer", "Pressure/Leg Ulcer"),
                            ("diabetic", "Diabetic Ulcer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="WoundCare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wound_id", models.CharField(max_length=20, unique=True)),
                (
                    "assessment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "laterality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("bilateral", "Bilateral"),
                            ("midline", "Midline"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "length_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Length in cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Width in cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "depth_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Depth in cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "surface_area_cm2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Surface area in cm²",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "appearance",
                    models.TextField(
                        blank=True, help_text="Describe wound appearance, color, etc."
                    ),
                ),
                (
                    "exudate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "No exudate"),
                            ("serous", "Serous (clear/straw)"),
                            ("seropurulent", "Seropurulent (cloudy/yellow)"),
                            ("purulent", "Purulent (thick/yellow-green)"),
                            ("sanguineous", "Sanguineous (blood)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "exudate_amount",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minimal", "Minimal"),
                            ("moderate", "Moderate"),
                            ("heavy", "Heavy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pain_level",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("has_edema", models.BooleanField(default=False)),
                (
                    "edema_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("mild", "Mild 1+"),
                            ("moderate", "Moderate 2+"),
                            ("severe", "Severe 3+"),
                            ("pitting", "Pitting 4+"),
                        ],
                        max_length=20,
                    ),
                ),
                ("signs_of_infection", models.BooleanField(default=False)),
                ("infection_notes", models.TextField(blank=True)),
                ("insurance_covers", models.BooleanField(default=False)),
                (
                    "copay_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Patient's copay %",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active Case"),
                            ("pending", "Pending Treatment"),
                            ("healing", "Healing"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("next_visit_date", models.DateField(blank=True, null=True)),
                ("clinical_notes", models.TextField(blank=True)),
                ("treatment_plan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wound_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "body_part",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.bodypart",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wound_cases",
                        to="core.patient",
                    ),
                ),
                (
                    "patient_insurance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.insuranceprovider",
                    ),
                ),
                (
                    "wound_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.woundtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="WoundBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "assessment_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "treatment_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dressing_supplies_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "medication_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("insurance_covers", models.BooleanField(default=False)),
                (
                    "insurance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "patient_copay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("check", "Check"),
                            ("mobile_money", "Mobile Money"),
                            ("insurance", "Insurance"),
                            ("waived", "Waived"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("partial", "Partially Paid"),
                            ("paid", "Fully Paid"),
                            ("waived", "Waived/Free"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wound",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing",
                        to="core.woundcare",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WoundFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "followup_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "wound_status",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("deteriorating", "Deteriorating"),
                            ("resolved", "Resolved"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "length_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "depth_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("appearance_notes", models.TextField(blank=True)),
                ("pain_level", models.IntegerField(default=0)),
                ("signs_of_infection", models.BooleanField(default=False)),
                ("treatment_adjusted", models.BooleanField(default=False)),
                ("adjustment_reason", models.TextField(blank=True)),
                ("next_followup_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="core.woundcare",
                    ),
                ),
            ],
            options={
                "ordering": ["-followup_date"],
            },
        ),
        migrations.CreateModel(
            name="WoundTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "treatment_type",
                    models.CharField(
                        choices=[
                            ("dressing_change", "Dressing Change"),
                            ("debridement", "Debridement"),
                            ("wound_wash", "Wound Wash/Irrigation"),
                            ("antiseptic", "Antiseptic/Antibiotic Application"),
                            ("compression", "Compression Therapy"),
                            ("vacuum_therapy", "Negative Pressure (VAC) Therapy"),
                            ("medication", "Medication Application"),
                            ("cultures", "Wound Culture/Sample"),
                            ("other", "Other Procedure"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of treatment performed"
                    ),
                ),
                (
                    "materials_used",
                    models.TextField(
                        blank=True, help_text="Dressings, antiseptics, gauze, etc."
                    ),
                ),
                (
                    "pain_after",
                    models.IntegerField(
                        default=0,
                        help_text="Pain level after (0-10)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("bleeding", models.BooleanField(default=False)),
                ("complications", models.TextField(blank=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Home care instructions for patient"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="core.woundcare",
                    ),
                ),
            ],
            options={
                "ordering": ["-treatment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="woundcare",
            index=models.Index(
                fields=["patient", "status"], name="core_woundc_patient_38a691_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="woundcare",
            index=models.Index(
                fields=["assessment_date"], name="core_woundc_assessm_75d252_idx"
            ),
        ),
    ]
