# Generated by Django 5.2.10 on 2026-01-29 15:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_insuranceclaim_paymenttransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporatePaymentScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "coverage_percentage",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "maximum_coverage_per_patient",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "days_to_pay",
                    models.IntegerField(
                        default=30, help_text="Days allowed before payment is due"
                    ),
                ),
                ("primary_contact_name", models.CharField(blank=True, max_length=100)),
                ("primary_contact_phone", models.CharField(blank=True, max_length=15)),
                (
                    "primary_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("billing_contact_name", models.CharField(blank=True, max_length=100)),
                ("billing_contact_phone", models.CharField(blank=True, max_length=15)),
                (
                    "billing_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_number", models.CharField(blank=True, max_length=30)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CreditAccountTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("charge", "Service Charge"),
                            ("payment", "Payment Received"),
                            ("credit", "Credit Adjustment"),
                            ("waiver", "Amount Waived"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=200)),
                (
                    "transaction_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("approval_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="PatientBillingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=20, unique=True)),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Maximum credit allowed",
                        max_digits=10,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current outstanding balance",
                        max_digits=10,
                    ),
                ),
                (
                    "available_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Available credit remaining",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_terms_days",
                    models.IntegerField(
                        default=30, help_text="Days allowed for payment"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("closed", "Closed"),
                            ("dormant", "Dormant"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Account verified by finance"
                    ),
                ),
                ("employer_name", models.CharField(blank=True, max_length=200)),
                ("employer_contact", models.CharField(blank=True, max_length=100)),
                ("employer_reference", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_payment_date", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="bank_account",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="card_last4",
            field=models.CharField(
                blank=True, help_text="Last 4 digits of card", max_length=4
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="card_reference",
            field=models.CharField(
                blank=True, help_text="Card processor reference", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="cheque_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Payment verified/confirmed"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="mpesa_phone",
            field=models.CharField(
                blank=True, help_text="M-Pesa phone number", max_length=15
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="mpesa_receipt",
            field=models.CharField(
                blank=True, help_text="M-Pesa STK confirmation code", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="refund_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="refund_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="refund_ref",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("mpesa", "M-Pesa"),
                    ("airtel_money", "Airtel Money"),
                    ("equity_bank", "Equity Bank"),
                    ("kcb_bank", "KCB Bank"),
                    ("co_op_bank", "Co-op Bank"),
                    ("other_bank", "Other Bank Transfer"),
                    ("card_visa", "Visa Card"),
                    ("card_mastercard", "Mastercard"),
                    ("card_debit", "Debit Card"),
                    ("insurance_claim", "Insurance Claim Payment"),
                    ("employer_scheme", "Employer/Corporate Scheme"),
                    ("credit_account", "Hospital Credit Account"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payment_method", "status"],
                name="core_paymen_payment_c99ddc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["mpesa_phone", "transaction_date"],
                name="core_paymen_mpesa_p_5ddf09_idx",
            ),
        ),
        migrations.AddField(
            model_name="corporatepaymentscheme",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corporate_schemes",
                to="core.insuranceprovider",
            ),
        ),
        migrations.AddField(
            model_name="creditaccounttransaction",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creditaccounttransaction",
            name="wound_billing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.woundbilling",
            ),
        ),
        migrations.AddField(
            model_name="patientbillingaccount",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_account",
                to="core.patient",
            ),
        ),
        migrations.AddField(
            model_name="creditaccounttransaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.patientbillingaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="patientbillingaccount",
            index=models.Index(
                fields=["patient", "status"], name="core_patien_patient_d487cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientbillingaccount",
            index=models.Index(
                fields=["account_number"], name="core_patien_account_007d1a_idx"
            ),
        ),
    ]
