# Generated by Django 5.2.10 on 2026-02-01 17:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_corporatepaymentscheme_creditaccounttransaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": [
                    ("view_patient", "Can view patient records"),
                    ("add_patient", "Can add new patients"),
                    ("change_patient", "Can modify patient records"),
                    ("delete_patient", "Can delete patient records"),
                    ("view_medical_history", "Can view patient medical history"),
                    ("add_medical_record", "Can add medical records"),
                    ("emergency_access", "Can access emergency patient data"),
                    ("view_appointment", "Can view appointments"),
                    ("add_appointment", "Can create appointments"),
                    ("change_appointment", "Can modify appointments"),
                    ("cancel_appointment", "Can cancel appointments"),
                    ("view_schedule", "Can view staff schedules"),
                    ("manage_schedule", "Can manage staff schedules"),
                    ("view_wound_case", "Can view wound cases"),
                    ("add_wound_case", "Can create wound cases"),
                    ("change_wound_case", "Can modify wound cases"),
                    ("treat_wound", "Can perform wound treatments"),
                    ("view_treatment_history", "Can view treatment history"),
                    ("manage_wound_billing", "Can manage wound billing"),
                    ("view_invoice", "Can view invoices"),
                    ("create_invoice", "Can create invoices"),
                    ("modify_invoice", "Can modify invoices"),
                    ("void_invoice", "Can void invoices"),
                    ("process_payment", "Can process payments"),
                    ("view_financial_reports", "Can view financial reports"),
                    ("manage_insurance", "Can manage insurance claims"),
                    ("view_lab_request", "Can view lab requests"),
                    ("create_lab_request", "Can create lab requests"),
                    ("process_lab_results", "Can process lab results"),
                    ("view_lab_reports", "Can view lab reports"),
                    ("manage_lab_inventory", "Can manage lab inventory"),
                    ("view_prescription", "Can view prescriptions"),
                    ("create_prescription", "Can create prescriptions"),
                    ("dispense_medication", "Can dispense medication"),
                    ("view_pharmacy_inventory", "Can view pharmacy inventory"),
                    ("manage_drug_inventory", "Can manage drug inventory"),
                    ("view_radiology_request", "Can view radiology requests"),
                    ("create_radiology_request", "Can create radiology requests"),
                    ("process_radiology_results", "Can process radiology results"),
                    ("view_imaging_reports", "Can view imaging reports"),
                    ("manage_users", "Can manage user accounts"),
                    ("manage_roles", "Can manage user roles"),
                    ("system_configuration", "Can configure system settings"),
                    ("view_audit_logs", "Can view audit logs"),
                    ("backup_system", "Can backup system data"),
                    ("restore_system", "Can restore system data"),
                    ("view_basic_reports", "Can view basic reports"),
                    ("view_advanced_reports", "Can view advanced reports"),
                    ("export_data", "Can export data"),
                    ("view_analytics_dashboard", "Can view analytics dashboard"),
                    ("create_custom_reports", "Can create custom reports"),
                ]
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="account_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="assigned_facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.clinic",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="custom_permissions",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional custom permissions"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_on_duty",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="lockout_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="working_hours_end",
            field=models.TimeField(default="17:00:00"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="working_hours_start",
            field=models.TimeField(default="08:00:00"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrator"),
                    ("admin", "System Administrator"),
                    ("doctor", "Doctor"),
                    ("nurse", "Nurse"),
                    ("cashier", "Cashier"),
                    ("lab_tech", "Laboratory Technician"),
                    ("pharmacist", "Pharmacist"),
                    ("receptionist", "Receptionist"),
                    ("radiologist", "Radiologist"),
                    ("hr_manager", "HR Manager"),
                    ("accountant", "Accountant"),
                    ("it_support", "IT Support"),
                    ("guest", "Guest/Read-Only"),
                ],
                default="guest",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("appointment", "Appointment"),
                            ("wound_care", "Wound Care"),
                            ("lab_result", "Lab Result"),
                            ("billing", "Billing"),
                            ("system", "System"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to redirect when notification is clicked",
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True, help_text="Text for action button", max_length=50
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.appointment",
                    ),
                ),
                (
                    "related_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.patient",
                    ),
                ),
                (
                    "related_wound",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.woundcare",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="core_notifi_recipie_4d7e73_idx",
                    ),
                    models.Index(
                        fields=["is_read", "recipient"],
                        name="core_notifi_is_read_cd4fd0_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="core_notifi_notific_cbfe88_idx",
                    ),
                ],
            },
        ),
    ]
